using Castle.Components.DictionaryAdapter;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;

namespace Models
{
    public class EntitiesContext : IdentityDbContext<User>
    {
        public EntitiesContext(DbContextOptions options) : base(options) { }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CheckList> CheckLists { get; set; }
        public DbSet<CheckListItem> CheckListItems { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Follow> Follows { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<PostAttachment> PostsAttachments { get; set; }
        public DbSet<PromoCode> PromoCodes { get; set; }
        public DbSet<React> Reacts { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<ServiceAttachment> ServiceAttachments { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<Invitation> Invitations { get; set; }
        public DbSet<Governorate> Governorates { get; set; }
        public DbSet<City> Cities { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new CategoryConfig());
            modelBuilder.ApplyConfiguration(new CheckListConfig());
            modelBuilder.ApplyConfiguration(new CheckListItemConfig());
            modelBuilder.ApplyConfiguration(new CommentConfig());
            modelBuilder.ApplyConfiguration(new FollowConfig());
            modelBuilder.ApplyConfiguration(new PostConfig());
            modelBuilder.ApplyConfiguration(new PostAttachmentConfig());
            modelBuilder.ApplyConfiguration(new PromoCodeConfig());
            modelBuilder.ApplyConfiguration(new ReactConfig());
            modelBuilder.ApplyConfiguration(new ReservationConfig());
            modelBuilder.ApplyConfiguration(new ReviewConfig());
            modelBuilder.ApplyConfiguration(new PaymentConfig());
            modelBuilder.ApplyConfiguration(new ServiceConfig());
            modelBuilder.ApplyConfiguration(new ServiceAttachmentConfig());
            modelBuilder.ApplyConfiguration(new UserConfig());
            modelBuilder.ApplyConfiguration(new VendorConfig());
            modelBuilder.ApplyConfiguration(new InvitationConfig());
            modelBuilder.ApplyConfiguration(new GovernorateConfig());
            modelBuilder.ApplyConfiguration(new CityConfig());

            #region DataSeeding
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, Name = "قاعة" },
                new Category { Id = 2, Name = "قاعة اسلامي" },
                new Category { Id = 3, Name = "نادي"},
                new Category { Id = 4, Name = "مصور" },
                new Category { Id = 5, Name = "مطعم" },
                new Category { Id = 6, Name = "صالون تجميل" },
                new Category { Id = 7, Name = "كوافير للرجال" },
                new Category { Id = 8, Name = "كوافير للسيدات" }
            );

            modelBuilder.Entity<IdentityRole>().HasData(
                new IdentityRole { Name = "user", NormalizedName = "USER" },
                new IdentityRole { Name = "vendor", NormalizedName = "VENDOR" },
                new IdentityRole { Name = "admin", NormalizedName = "ADMIN" });

            modelBuilder.Entity<Governorate>().HasData(
                new Governorate { Id = 1, NameAr = "القاهرة", NameEn = "Cairo" },
                new Governorate { Id = 2, NameAr = "الجيزة", NameEn = "Giza" },
                new Governorate { Id = 3, NameAr = "الأسكندرية", NameEn = "Alexandria" },
                new Governorate { Id = 4, NameAr = "الدقهلية", NameEn = "Dakahlia" },
                new Governorate { Id = 5, NameAr = "البحر الأحمر", NameEn = "Red Sea" },
                new Governorate { Id = 6, NameAr = "البحيرة", NameEn = "Beheira" },
                new Governorate { Id = 7, NameAr = "الفيوم", NameEn = "Fayoum" },
                new Governorate { Id = 8, NameAr = "الغربية", NameEn = "Gharbiya" },
                new Governorate { Id = 9, NameAr = "الإسماعلية", NameEn = "Ismailia" },
                new Governorate { Id = 10, NameAr = "المنوفية", NameEn = "Menofia" },
                new Governorate { Id = 11, NameAr = "المنيا", NameEn = "Minya" },
                new Governorate { Id = 12, NameAr = "القليوبية", NameEn = "Qaliubiya" },
                new Governorate { Id = 13, NameAr = "الوادي الجديد", NameEn = "New Valley" },
                new Governorate { Id = 14, NameAr = "السويس", NameEn = "Suez" },
                new Governorate { Id = 15, NameAr = "اسوان", NameEn = "Aswan" },
                new Governorate { Id = 16, NameAr = "اسيوط", NameEn = "Assiut" },
                new Governorate { Id = 17, NameAr = "بني سويف", NameEn = "Beni Suef" },
                new Governorate { Id = 18, NameAr = "بورسعيد", NameEn = "Port SaId" },
                new Governorate { Id = 19, NameAr = "دمياط", NameEn = "Damietta" },
                new Governorate { Id = 20, NameAr = "الشرقية", NameEn = "Sharkia" },
                new Governorate { Id = 21, NameAr = "جنوب سيناء", NameEn = "South Sinai" },
                new Governorate { Id = 22, NameAr = "كفر الشيخ", NameEn = "Kafr Al sheikh" },
                new Governorate { Id = 23, NameAr = "مطروح", NameEn = "Matrouh" },
                new Governorate { Id = 24, NameAr = "الأقصر", NameEn = "Luxor" },
                new Governorate { Id = 25, NameAr = "قنا", NameEn = "Qena" },
                new Governorate { Id = 26, NameAr = "شمال سيناء", NameEn = "North Sinai" },
                new Governorate { Id = 27, NameAr = "سوهاج", NameEn = "Sohag" }
            );

            modelBuilder.Entity<City>().HasData(
                new City { Id = 1, GovernorateId = 1, NameAr = "15 مايو", NameEn = "15 May" },
                new City { Id = 2, GovernorateId = 1, NameAr = "الازبكية", NameEn = "Al Azbakeyah" },
                new City { Id = 3, GovernorateId = 1, NameAr = "البساتين", NameEn = "Al Basatin" },
                new City { Id = 4, GovernorateId = 1, NameAr = "التبين", NameEn = "Tebin" },
                new City { Id = 5, GovernorateId = 1, NameAr = "الخليفة", NameEn = "El-Khalifa" },
                new City { Id = 6, GovernorateId = 1, NameAr = "الدراسة", NameEn = "El darrasa" },
                new City { Id = 7, GovernorateId = 1, NameAr = "الدرب الاحمر", NameEn = "Aldarb Alahmar" },
                new City { Id = 8, GovernorateId = 1, NameAr = "الزاوية الحمراء", NameEn = "Zawya al-Hamra" },
                new City { Id = 9, GovernorateId = 1, NameAr = "الزيتون", NameEn = "El-Zaytoun" },
                new City { Id = 10, GovernorateId = 1, NameAr = "الساحل", NameEn = "Sahel" },
                new City { Id = 11, GovernorateId = 1, NameAr = "السلام", NameEn = "El Salam" },
                new City { Id = 12, GovernorateId = 1, NameAr = "السيدة زينب", NameEn = "Sayeda Zeinab" },
                new City { Id = 13, GovernorateId = 1, NameAr = "الشرابية", NameEn = "El Sharabeya" },
                new City { Id = 14, GovernorateId = 1, NameAr = "مدينة الشروق", NameEn = "Shorouk" },
                new City { Id = 15, GovernorateId = 1, NameAr = "الظاهر", NameEn = "El Daher" },
                new City { Id = 16, GovernorateId = 1, NameAr = "العتبة", NameEn = "Ataba" },
                new City { Id = 17, GovernorateId = 1, NameAr = "القاهرة الجديدة", NameEn = "New Cairo" },
                new City { Id = 18, GovernorateId = 1, NameAr = "المرج", NameEn = "El Marg" },
                new City { Id = 19, GovernorateId = 1, NameAr = "عزبة النخل", NameEn = "Ezbet el Nakhl" },
                new City { Id = 20, GovernorateId = 1, NameAr = "المطرية", NameEn = "Matareya" },
                new City { Id = 21, GovernorateId = 1, NameAr = "المعادى", NameEn = "Maadi" },
                new City { Id = 22, GovernorateId = 1, NameAr = "المعصرة", NameEn = "Maasara" },
                new City { Id = 23, GovernorateId = 1, NameAr = "المقطم", NameEn = "Mokattam" },
                new City { Id = 24, GovernorateId = 1, NameAr = "المنيل", NameEn = "Manyal" },
                new City { Id = 25, GovernorateId = 1, NameAr = "الموسكى", NameEn = "Mosky" },
                new City { Id = 26, GovernorateId = 1, NameAr = "النزهة", NameEn = "Nozha" },
                new City { Id = 27, GovernorateId = 1, NameAr = "الوايلى", NameEn = "Waily" },
                new City { Id = 28, GovernorateId = 1, NameAr = "باب الشعرية", NameEn = "Bab al-Shereia" },
                new City { Id = 29, GovernorateId = 1, NameAr = "بولاق", NameEn = "Bolaq" },
                new City { Id = 30, GovernorateId = 1, NameAr = "جاردن سيتى", NameEn = "Garden City" },
                new City { Id = 31, GovernorateId = 1, NameAr = "حدائق القبة", NameEn = "Hadayek El-Kobba" },
                new City { Id = 32, GovernorateId = 1, NameAr = "حلوان", NameEn = "Helwan" },
                new City { Id = 33, GovernorateId = 1, NameAr = "دار السلام", NameEn = "Dar Al Salam" },
                new City { Id = 34, GovernorateId = 1, NameAr = "شبرا", NameEn = "Shubra" },
                new City { Id = 35, GovernorateId = 1, NameAr = "طره", NameEn = "Tura" },
                new City { Id = 36, GovernorateId = 1, NameAr = "عابدين", NameEn = "Abdeen" },
                new City { Id = 37, GovernorateId = 1, NameAr = "عباسية", NameEn = "Abaseya" },
                new City { Id = 38, GovernorateId = 1, NameAr = "عين شمس", NameEn = "Ain Shams" },
                new City { Id = 39, GovernorateId = 1, NameAr = "مدينة نصر", NameEn = "Nasr City" },
                new City { Id = 40, GovernorateId = 1, NameAr = "مصر الجديدة", NameEn = "New Heliopolis" },
                new City { Id = 41, GovernorateId = 1, NameAr = "مصر القديمة", NameEn = "Masr Al Qadima" },
                new City { Id = 42, GovernorateId = 1, NameAr = "منشية ناصر", NameEn = "Mansheya Nasir" },
                new City { Id = 43, GovernorateId = 1, NameAr = "مدينة بدر", NameEn = "Badr City" },
                new City { Id = 44, GovernorateId = 1, NameAr = "مدينة العبور", NameEn = "Obour City" },
                new City { Id = 45, GovernorateId = 1, NameAr = "وسط البلد", NameEn = "Cairo Downtown" },
                new City { Id = 46, GovernorateId = 1, NameAr = "الزمالك", NameEn = "Zamalek" },
                new City { Id = 47, GovernorateId = 1, NameAr = "قصر النيل", NameEn = "Kasr El Nile" },
                new City { Id = 48, GovernorateId = 1, NameAr = "الرحاب", NameEn = "Rehab" },
                new City { Id = 49, GovernorateId = 1, NameAr = "القطامية", NameEn = "Katameya" },
                new City { Id = 50, GovernorateId = 1, NameAr = "مدينتي", NameEn = "Madinty" },
                new City { Id = 51, GovernorateId = 1, NameAr = "روض الفرج", NameEn = "Rod Alfarag" },
                new City { Id = 52, GovernorateId = 1, NameAr = "شيراتون", NameEn = "Sheraton" },
                new City { Id = 53, GovernorateId = 1, NameAr = "الجمالية", NameEn = "El-Gamaleya" },
                new City { Id = 54, GovernorateId = 1, NameAr = "العاشر من رمضان", NameEn = "10th of Ramadan City" },
                new City { Id = 55, GovernorateId = 1, NameAr = "الحلمية", NameEn = "Helmeyat Alzaytoun" },
                new City { Id = 56, GovernorateId = 1, NameAr = "النزهة الجديدة", NameEn = "New Nozha" },
                new City { Id = 57, GovernorateId = 1, NameAr = "العاصمة الإدارية", NameEn = "Capital New" },
                new City { Id = 58, GovernorateId = 2, NameAr = "الجيزة", NameEn = "Giza" },
                new City { Id = 59, GovernorateId = 2, NameAr = "السادس من أكتوبر", NameEn = "Sixth of October" },
                new City { Id = 60, GovernorateId = 2, NameAr = "الشيخ زايد", NameEn = "Cheikh Zayed" },
                new City { Id = 61, GovernorateId = 2, NameAr = "الحوامدية", NameEn = "Hawamdiyah" },
                new City { Id = 62, GovernorateId = 2, NameAr = "البدرشين", NameEn = "Al Badrasheen" },
                new City { Id = 63, GovernorateId = 2, NameAr = "الصف", NameEn = "Saf" },
                new City { Id = 64, GovernorateId = 2, NameAr = "أطفيح", NameEn = "Atfih" },
                new City { Id = 65, GovernorateId = 2, NameAr = "العياط", NameEn = "Al Ayat" },
                new City { Id = 66, GovernorateId = 2, NameAr = "الباويطي", NameEn = "Al-Bawaiti" },
                new City { Id = 67, GovernorateId = 2, NameAr = "منشأة القناطر", NameEn = "ManshiyetAl Qanater" },
                new City { Id = 68, GovernorateId = 2, NameAr = "أوسيم", NameEn = "Oaseem" },
                new City { Id = 69, GovernorateId = 2, NameAr = "كرداسة", NameEn = "Kerdasa" },
                new City { Id = 70, GovernorateId = 2, NameAr = "أبو النمرس", NameEn = "Abu Nomros" },
                new City { Id = 71, GovernorateId = 2, NameAr = "كفر غطاطي", NameEn = "Kafr Ghati" },
                new City { Id = 72, GovernorateId = 2, NameAr = "منشأة البكاري", NameEn = "Manshiyet Al Bakari" },
                new City { Id = 73, GovernorateId = 2, NameAr = "الدقى", NameEn = "Dokki" },
                new City { Id = 74, GovernorateId = 2, NameAr = "العجوزة", NameEn = "Agouza" },
                new City { Id = 75, GovernorateId = 2, NameAr = "الهرم", NameEn = "Haram" },
                new City { Id = 76, GovernorateId = 2, NameAr = "الوراق", NameEn = "Warraq" },
                new City { Id = 77, GovernorateId = 2, NameAr = "امبابة", NameEn = "Imbaba" },
                new City { Id = 78, GovernorateId = 2, NameAr = "بولاق الدكرور", NameEn = "Boulaq Dakrour" },
                new City { Id = 79, GovernorateId = 2, NameAr = "الواحات البحرية", NameEn = "Al Wahat Al Baharia" },
                new City { Id = 80, GovernorateId = 2, NameAr = "العمرانية", NameEn = "Omraneya" },
                new City { Id = 81, GovernorateId = 2, NameAr = "المنيب", NameEn = "Moneeb" },
                new City { Id = 82, GovernorateId = 2, NameAr = "بين السرايات", NameEn = "Bin Alsarayat" },
                new City { Id = 83, GovernorateId = 2, NameAr = "الكيت كات", NameEn = "Kit Kat" },
                new City { Id = 84, GovernorateId = 2, NameAr = "المهندسين", NameEn = "Mohandessin" },
                new City { Id = 85, GovernorateId = 2, NameAr = "فيصل", NameEn = "Faisal" },
                new City { Id = 86, GovernorateId = 2, NameAr = "أبو رواش", NameEn = "Abu Rawash" },
                new City { Id = 87, GovernorateId = 2, NameAr = "حدائق الأهرام", NameEn = "Hadayek Alahram" },
                new City { Id = 88, GovernorateId = 2, NameAr = "الحرانية", NameEn = "Haraneya" },
                new City { Id = 89, GovernorateId = 2, NameAr = "حدائق اكتوبر", NameEn = "Hadayek October" },
                new City { Id = 90, GovernorateId = 2, NameAr = "صفط اللبن", NameEn = "Saft Allaban" },
                new City { Id = 91, GovernorateId = 2, NameAr = "القرية الذكية", NameEn = "Smart Village" },
                new City { Id = 92, GovernorateId = 2, NameAr = "ارض اللواء", NameEn = "Ard Ellwaa" },
                new City { Id = 93, GovernorateId = 3, NameAr = "ابو قير", NameEn = "Abu Qir" },
                new City { Id = 94, GovernorateId = 3, NameAr = "الابراهيمية", NameEn = "Al Ibrahimeyah" },
                new City { Id = 95, GovernorateId = 3, NameAr = "الأزاريطة", NameEn = "Azarita" },
                new City { Id = 96, GovernorateId = 3, NameAr = "الانفوشى", NameEn = "Anfoushi" },
                new City { Id = 97, GovernorateId = 3, NameAr = "الدخيلة", NameEn = "Dekheila" },
                new City { Id = 98, GovernorateId = 3, NameAr = "السيوف", NameEn = "El Soyof" },
                new City { Id = 99, GovernorateId = 3, NameAr = "العامرية", NameEn = "Ameria" },
                new City { Id = 100, GovernorateId = 3, NameAr = "اللبان", NameEn = "El Labban" },
                new City { Id = 101, GovernorateId = 3, NameAr = "المفروزة", NameEn = "Al Mafrouza" },
                new City { Id = 102, GovernorateId = 3, NameAr = "المنتزه", NameEn = "El Montaza" },
                new City { Id = 103, GovernorateId = 3, NameAr = "المنشية", NameEn = "Mansheya" },
                new City { Id = 104, GovernorateId = 3, NameAr = "الناصرية", NameEn = "Naseria" },
                new City { Id = 105, GovernorateId = 3, NameAr = "امبروزو", NameEn = "Ambrozo" },
                new City { Id = 106, GovernorateId = 3, NameAr = "باب شرق", NameEn = "Bab Sharq" },
                new City { Id = 107, GovernorateId = 3, NameAr = "برج العرب", NameEn = "Bourj Alarab" },
                new City { Id = 108, GovernorateId = 3, NameAr = "ستانلى", NameEn = "Stanley" },
                new City { Id = 109, GovernorateId = 3, NameAr = "سموحة", NameEn = "Smouha" },
                new City { Id = 110, GovernorateId = 3, NameAr = "سيدى بشر", NameEn = "SIdi Bishr" },
                new City { Id = 111, GovernorateId = 3, NameAr = "شدس", NameEn = "Shads" },
                new City { Id = 112, GovernorateId = 3, NameAr = "غيط العنب", NameEn = "Gheet Alenab" },
                new City { Id = 113, GovernorateId = 3, NameAr = "فلمينج", NameEn = "Fleming" },
                new City { Id = 114, GovernorateId = 3, NameAr = "فيكتوريا", NameEn = "Victoria" },
                new City { Id = 115, GovernorateId = 3, NameAr = "كامب شيزار", NameEn = "Camp Shizar" },
                new City { Id = 116, GovernorateId = 3, NameAr = "كرموز", NameEn = "Karmooz" },
                new City { Id = 117, GovernorateId = 3, NameAr = "محطة الرمل", NameEn = "Mahta Alraml" },
                new City { Id = 118, GovernorateId = 3, NameAr = "مينا البصل", NameEn = "Mina El-Basal" },
                new City { Id = 119, GovernorateId = 3, NameAr = "العصافرة", NameEn = "Asafra" },
                new City { Id = 120, GovernorateId = 3, NameAr = "العجمي", NameEn = "Agamy" },
                new City { Id = 121, GovernorateId = 3, NameAr = "بكوس", NameEn = "Bakos" },
                new City { Id = 122, GovernorateId = 3, NameAr = "بولكلي", NameEn = "Boulkly" },
                new City { Id = 123, GovernorateId = 3, NameAr = "كليوباترا", NameEn = "Cleopatra" },
                new City { Id = 124, GovernorateId = 3, NameAr = "جليم", NameEn = "Glim" },
                new City { Id = 125, GovernorateId = 3, NameAr = "المعمورة", NameEn = "Al Mamurah" },
                new City { Id = 126, GovernorateId = 3, NameAr = "المندرة", NameEn = "Al Mandara" },
                new City { Id = 127, GovernorateId = 3, NameAr = "محرم بك", NameEn = "Moharam Bek" },
                new City { Id = 128, GovernorateId = 3, NameAr = "الشاطبي", NameEn = "Elshatby" },
                new City { Id = 129, GovernorateId = 3, NameAr = "سيدي جابر", NameEn = "SIdi Gaber" },
                new City { Id = 130, GovernorateId = 3, NameAr = "الساحل الشمالي", NameEn = "North Coast Sahel" },
                new City { Id = 131, GovernorateId = 3, NameAr = "الحضرة", NameEn = "Alhadra" },
                new City { Id = 132, GovernorateId = 3, NameAr = "العطارين", NameEn = "Alattarin" },
                new City { Id = 133, GovernorateId = 3, NameAr = "سيدي كرير", NameEn = "SIdi Kerir" },
                new City { Id = 134, GovernorateId = 3, NameAr = "الجمرك", NameEn = "Elgomrok" },
                new City { Id = 135, GovernorateId = 3, NameAr = "المكس", NameEn = "Al Max" },
                new City { Id = 136, GovernorateId = 3, NameAr = "مارينا", NameEn = "Marina" },
                new City { Id = 137, GovernorateId = 4, NameAr = "المنصورة", NameEn = "Mansoura" },
                new City { Id = 138, GovernorateId = 4, NameAr = "طلخا", NameEn = "Talkha" },
                new City { Id = 139, GovernorateId = 4, NameAr = "ميت غمر", NameEn = "Mitt Ghamr" },
                new City { Id = 140, GovernorateId = 4, NameAr = "دكرنس", NameEn = "Dekernes" },
                new City { Id = 141, GovernorateId = 4, NameAr = "أجا", NameEn = "Aga" },
                new City { Id = 142, GovernorateId = 4, NameAr = "منية النصر", NameEn = "Menia El Nasr" },
                new City { Id = 143, GovernorateId = 4, NameAr = "السنبلاوين", NameEn = "Sinbillawin" },
                new City { Id = 144, GovernorateId = 4, NameAr = "الكردي", NameEn = "El Kurdi" },
                new City { Id = 145, GovernorateId = 4, NameAr = "بني عبيد", NameEn = "Bani UbaId" },
                new City { Id = 146, GovernorateId = 4, NameAr = "المنزلة", NameEn = "Al Manzala" },
                new City { Id = 147, GovernorateId = 4, NameAr = "تمي الأمديد", NameEn = "tami al'amdId" },
                new City { Id = 148, GovernorateId = 4, NameAr = "الجمالية", NameEn = "aljamalia" },
                new City { Id = 149, GovernorateId = 4, NameAr = "شربين", NameEn = "Sherbin" },
                new City { Id = 150, GovernorateId = 4, NameAr = "المطرية", NameEn = "Mataria" },
                new City { Id = 151, GovernorateId = 4, NameAr = "بلقاس", NameEn = "Belqas" },
                new City { Id = 152, GovernorateId = 4, NameAr = "ميت سلسيل", NameEn = "Meet Salsil" },
                new City { Id = 153, GovernorateId = 4, NameAr = "جمصة", NameEn = "Gamasa" },
                new City { Id = 154, GovernorateId = 4, NameAr = "محلة دمنة", NameEn = "Mahalat Damana" },
                new City { Id = 155, GovernorateId = 4, NameAr = "نبروه", NameEn = "Nabroh" },
                new City { Id = 156, GovernorateId = 5, NameAr = "الغردقة", NameEn = "Hurghada" },
                new City { Id = 157, GovernorateId = 5, NameAr = "رأس غارب", NameEn = "Ras Ghareb" },
                new City { Id = 158, GovernorateId = 5, NameAr = "سفاجا", NameEn = "Safaga" },
                new City { Id = 159, GovernorateId = 5, NameAr = "القصير", NameEn = "El Qusiar" },
                new City { Id = 160, GovernorateId = 5, NameAr = "مرسى علم", NameEn = "Marsa Alam" },
                new City { Id = 161, GovernorateId = 5, NameAr = "الشلاتين", NameEn = "Shalatin" },
                new City { Id = 162, GovernorateId = 5, NameAr = "حلايب", NameEn = "Halaib" },
                new City { Id = 163, GovernorateId = 5, NameAr = "الدهار", NameEn = "Aldahar" },
                new City { Id = 164, GovernorateId = 6, NameAr = "دمنهور", NameEn = "Damanhour" },
                new City { Id = 165, GovernorateId = 6, NameAr = "كفر الدوار", NameEn = "Kafr El Dawar" },
                new City { Id = 166, GovernorateId = 6, NameAr = "رشيد", NameEn = "RashId" },
                new City { Id = 167, GovernorateId = 6, NameAr = "إدكو", NameEn = "Edco" },
                new City { Id = 168, GovernorateId = 6, NameAr = "أبو المطامير", NameEn = "Abu al-Matamir" },
                new City { Id = 169, GovernorateId = 6, NameAr = "أبو حمص", NameEn = "Abu Homs" },
                new City { Id = 170, GovernorateId = 6, NameAr = "الدلنجات", NameEn = "Delengat" },
                new City { Id = 171, GovernorateId = 6, NameAr = "المحمودية", NameEn = "Mahmoudiyah" },
                new City { Id = 172, GovernorateId = 6, NameAr = "الرحمانية", NameEn = "Rahmaniyah" },
                new City { Id = 173, GovernorateId = 6, NameAr = "إيتاي البارود", NameEn = "Itai Baroud" },
                new City { Id = 174, GovernorateId = 6, NameAr = "حوش عيسى", NameEn = "Housh Eissa" },
                new City { Id = 175, GovernorateId = 6, NameAr = "شبراخيت", NameEn = "Shubrakhit" },
                new City { Id = 176, GovernorateId = 6, NameAr = "كوم حمادة", NameEn = "Kom Hamada" },
                new City { Id = 177, GovernorateId = 6, NameAr = "بدر", NameEn = "Badr" },
                new City { Id = 178, GovernorateId = 6, NameAr = "وادي النطرون", NameEn = "Wadi Natrun" },
                new City { Id = 179, GovernorateId = 6, NameAr = "النوبارية الجديدة", NameEn = "New Nubaria" },
                new City { Id = 180, GovernorateId = 6, NameAr = "النوبارية", NameEn = "Alnoubareya" },
                new City { Id = 181, GovernorateId = 7, NameAr = "الفيوم", NameEn = "Fayoum" },
                new City { Id = 182, GovernorateId = 7, NameAr = "الفيوم الجديدة", NameEn = "Fayoum El GedIda" },
                new City { Id = 183, GovernorateId = 7, NameAr = "طامية", NameEn = "Tamiya" },
                new City { Id = 184, GovernorateId = 7, NameAr = "سنورس", NameEn = "Snores" },
                new City { Id = 185, GovernorateId = 7, NameAr = "إطسا", NameEn = "Etsa" },
                new City { Id = 186, GovernorateId = 7, NameAr = "إبشواي", NameEn = "Epschway" },
                new City { Id = 187, GovernorateId = 7, NameAr = "يوسف الصديق", NameEn = "Yusuf El Sediaq" },
                new City { Id = 188, GovernorateId = 7, NameAr = "الحادقة", NameEn = "Hadqa" },
                new City { Id = 189, GovernorateId = 7, NameAr = "اطسا", NameEn = "Atsa" },
                new City { Id = 190, GovernorateId = 7, NameAr = "الجامعة", NameEn = "Algamaa" },
                new City { Id = 191, GovernorateId = 7, NameAr = "السيالة", NameEn = "Sayala" },
                new City { Id = 192, GovernorateId = 8, NameAr = "طنطا", NameEn = "Tanta" },
                new City { Id = 193, GovernorateId = 8, NameAr = "المحلة الكبرى", NameEn = "Al Mahalla Al Kobra" },
                new City { Id = 194, GovernorateId = 8, NameAr = "كفر الزيات", NameEn = "Kafr El Zayat" },
                new City { Id = 195, GovernorateId = 8, NameAr = "زفتى", NameEn = "Zefta" },
                new City { Id = 196, GovernorateId = 8, NameAr = "السنطة", NameEn = "El Santa" },
                new City { Id = 197, GovernorateId = 8, NameAr = "قطور", NameEn = "Qutour" },
                new City { Id = 198, GovernorateId = 8, NameAr = "بسيون", NameEn = "Basion" },
                new City { Id = 199, GovernorateId = 8, NameAr = "سمنود", NameEn = "Samannoud" },
                new City { Id = 200, GovernorateId = 9, NameAr = "الإسماعيلية", NameEn = "Ismailia" },
                new City { Id = 201, GovernorateId = 9, NameAr = "فايد", NameEn = "Fayed" },
                new City { Id = 202, GovernorateId = 9, NameAr = "القنطرة شرق", NameEn = "Qantara Sharq" },
                new City { Id = 203, GovernorateId = 9, NameAr = "القنطرة غرب", NameEn = "Qantara Gharb" },
                new City { Id = 204, GovernorateId = 9, NameAr = "التل الكبير", NameEn = "El Tal El Kabier" },
                new City { Id = 205, GovernorateId = 9, NameAr = "أبو صوير", NameEn = "Abu Sawir" },
                new City { Id = 206, GovernorateId = 9, NameAr = "القصاصين الجديدة", NameEn = "Kasasien El GedIda" },
                new City { Id = 207, GovernorateId = 9, NameAr = "نفيشة", NameEn = "Nefesha" },
                new City { Id = 208, GovernorateId = 9, NameAr = "الشيخ زايد", NameEn = "Sheikh Zayed" },
                new City { Id = 209, GovernorateId = 10, NameAr = "شبين الكوم", NameEn = "Shbeen El Koom" },
                new City { Id = 210, GovernorateId = 10, NameAr = "مدينة السادات", NameEn = "Sadat City" },
                new City { Id = 211, GovernorateId = 10, NameAr = "منوف", NameEn = "Menouf" },
                new City { Id = 212, GovernorateId = 10, NameAr = "سرس الليان", NameEn = "Sars El-Layan" },
                new City { Id = 213, GovernorateId = 10, NameAr = "أشمون", NameEn = "Ashmon" },
                new City { Id = 214, GovernorateId = 10, NameAr = "الباجور", NameEn = "Al Bagor" },
                new City { Id = 215, GovernorateId = 10, NameAr = "قويسنا", NameEn = "Quesna" },
                new City { Id = 216, GovernorateId = 10, NameAr = "بركة السبع", NameEn = "Berkat El Saba" },
                new City { Id = 217, GovernorateId = 10, NameAr = "تلا", NameEn = "Tala" },
                new City { Id = 218, GovernorateId = 10, NameAr = "الشهداء", NameEn = "Al Shohada" },
                new City { Id = 219, GovernorateId = 11, NameAr = "المنيا", NameEn = "Minya" },
                new City { Id = 220, GovernorateId = 11, NameAr = "المنيا الجديدة", NameEn = "Minya El GedIda" },
                new City { Id = 221, GovernorateId = 11, NameAr = "العدوة", NameEn = "El Adwa" },
                new City { Id = 222, GovernorateId = 11, NameAr = "مغاغة", NameEn = "Magagha" },
                new City { Id = 223, GovernorateId = 11, NameAr = "بني مزار", NameEn = "Bani Mazar" },
                new City { Id = 224, GovernorateId = 11, NameAr = "مطاي", NameEn = "Mattay" },
                new City { Id = 225, GovernorateId = 11, NameAr = "سمالوط", NameEn = "Samalut" },
                new City { Id = 226, GovernorateId = 11, NameAr = "المدينة الفكرية", NameEn = "Madinat El Fekria" },
                new City { Id = 227, GovernorateId = 11, NameAr = "ملوي", NameEn = "Meloy" },
                new City { Id = 228, GovernorateId = 11, NameAr = "دير مواس", NameEn = "Deir Mawas" },
                new City { Id = 229, GovernorateId = 11, NameAr = "ابو قرقاص", NameEn = "Abu Qurqas" },
                new City { Id = 230, GovernorateId = 11, NameAr = "ارض سلطان", NameEn = "Ard Sultan" },
                new City { Id = 231, GovernorateId = 12, NameAr = "بنها", NameEn = "Banha" },
                new City { Id = 232, GovernorateId = 12, NameAr = "قليوب", NameEn = "Qalyub" },
                new City { Id = 233, GovernorateId = 12, NameAr = "شبرا الخيمة", NameEn = "Shubra Al Khaimah" },
                new City { Id = 234, GovernorateId = 12, NameAr = "القناطر الخيرية", NameEn = "Al Qanater Charity" },
                new City { Id = 235, GovernorateId = 12, NameAr = "الخانكة", NameEn = "Khanka" },
                new City { Id = 236, GovernorateId = 12, NameAr = "كفر شكر", NameEn = "Kafr Shukr" },
                new City { Id = 237, GovernorateId = 12, NameAr = "طوخ", NameEn = "Tukh" },
                new City { Id = 238, GovernorateId = 12, NameAr = "قها", NameEn = "Qaha" },
                new City { Id = 239, GovernorateId = 12, NameAr = "العبور", NameEn = "Obour" },
                new City { Id = 240, GovernorateId = 12, NameAr = "الخصوص", NameEn = "Khosous" },
                new City { Id = 241, GovernorateId = 12, NameAr = "شبين القناطر", NameEn = "Shibin Al Qanater" },
                new City { Id = 242, GovernorateId = 12, NameAr = "مسطرد", NameEn = "Mostorod" },
                new City { Id = 243, GovernorateId = 13, NameAr = "الخارجة", NameEn = "El Kharga" },
                new City { Id = 244, GovernorateId = 13, NameAr = "باريس", NameEn = "Paris" },
                new City { Id = 245, GovernorateId = 13, NameAr = "موط", NameEn = "Mout" },
                new City { Id = 246, GovernorateId = 13, NameAr = "الفرافرة", NameEn = "Farafra" },
                new City { Id = 247, GovernorateId = 13, NameAr = "بلاط", NameEn = "Balat" },
                new City { Id = 248, GovernorateId = 13, NameAr = "الداخلة", NameEn = "Dakhla" },
                new City { Id = 249, GovernorateId = 14, NameAr = "السويس", NameEn = "Suez" },
                new City { Id = 250, GovernorateId = 14, NameAr = "الجناين", NameEn = "Alganayen" },
                new City { Id = 251, GovernorateId = 14, NameAr = "عتاقة", NameEn = "Ataqah" },
                new City { Id = 252, GovernorateId = 14, NameAr = "العين السخنة", NameEn = "Ain Sokhna" },
                new City { Id = 253, GovernorateId = 14, NameAr = "فيصل", NameEn = "Faysal" },
                new City { Id = 254, GovernorateId = 15, NameAr = "أسوان", NameEn = "Aswan" },
                new City { Id = 255, GovernorateId = 15, NameAr = "أسوان الجديدة", NameEn = "Aswan El GedIda" },
                new City { Id = 256, GovernorateId = 15, NameAr = "دراو", NameEn = "Drau" },
                new City { Id = 257, GovernorateId = 15, NameAr = "كوم أمبو", NameEn = "Kom Ombo" },
                new City { Id = 258, GovernorateId = 15, NameAr = "نصر النوبة", NameEn = "Nasr Al Nuba" },
                new City { Id = 259, GovernorateId = 15, NameAr = "كلابشة", NameEn = "Kalabsha" },
                new City { Id = 260, GovernorateId = 15, NameAr = "إدفو", NameEn = "Edfu" },
                new City { Id = 261, GovernorateId = 15, NameAr = "الرديسية", NameEn = "Al-Radisiyah" },
                new City { Id = 262, GovernorateId = 15, NameAr = "البصيلية", NameEn = "Al Basilia" },
                new City { Id = 263, GovernorateId = 15, NameAr = "السباعية", NameEn = "Al Sibaeia" },
                new City { Id = 264, GovernorateId = 15, NameAr = "ابوسمبل السياحية", NameEn = "Abo Simbl Al Siyahia" },
                new City { Id = 266, GovernorateId = 16, NameAr = "أسيوط", NameEn = "Assiut" },
                new City { Id = 267, GovernorateId = 16, NameAr = "أسيوط الجديدة", NameEn = "Assiut El GedIda" },
                new City { Id = 268, GovernorateId = 16, NameAr = "ديروط", NameEn = "Dayrout" },
                new City { Id = 269, GovernorateId = 16, NameAr = "منفلوط", NameEn = "Manfalut" },
                new City { Id = 270, GovernorateId = 16, NameAr = "القوصية", NameEn = "Qusiya" },
                new City { Id = 271, GovernorateId = 16, NameAr = "أبنوب", NameEn = "Abnoub" },
                new City { Id = 272, GovernorateId = 16, NameAr = "أبو تيج", NameEn = "Abu Tig" },
                new City { Id = 273, GovernorateId = 16, NameAr = "الغنايم", NameEn = "El Ghanaim" },
                new City { Id = 274, GovernorateId = 16, NameAr = "ساحل سليم", NameEn = "Sahel Selim" },
                new City { Id = 275, GovernorateId = 16, NameAr = "البداري", NameEn = "El Badari" },
                new City { Id = 276, GovernorateId = 16, NameAr = "صدفا", NameEn = "SIdfa" },
                new City { Id = 277, GovernorateId = 17, NameAr = "بني سويف", NameEn = "Bani Sweif" },
                new City { Id = 278, GovernorateId = 17, NameAr = "بني سويف الجديدة", NameEn = "Beni Suef El GedIda" },
                new City { Id = 279, GovernorateId = 17, NameAr = "الواسطى", NameEn = "Al Wasta" },
                new City { Id = 280, GovernorateId = 17, NameAr = "ناصر", NameEn = "Naser" },
                new City { Id = 281, GovernorateId = 17, NameAr = "إهناسيا", NameEn = "Ehnasia" },
                new City { Id = 282, GovernorateId = 17, NameAr = "ببا", NameEn = "beba" },
                new City { Id = 283, GovernorateId = 17, NameAr = "الفشن", NameEn = "Fashn" },
                new City { Id = 284, GovernorateId = 17, NameAr = "سمسطا", NameEn = "Somasta" },
                new City { Id = 285, GovernorateId = 17, NameAr = "الاباصيرى", NameEn = "Alabbaseri" },
                new City { Id = 286, GovernorateId = 17, NameAr = "مقبل", NameEn = "Mokbel" },
                new City { Id = 287, GovernorateId = 18, NameAr = "بورسعيد", NameEn = "PorSaId" },
                new City { Id = 288, GovernorateId = 18, NameAr = "بورفؤاد", NameEn = "Port Fouad" },
                new City { Id = 289, GovernorateId = 18, NameAr = "العرب", NameEn = "Alarab" },
                new City { Id = 290, GovernorateId = 18, NameAr = "حى الزهور", NameEn = "Zohour" },
                new City { Id = 291, GovernorateId = 18, NameAr = "حى الشرق", NameEn = "Alsharq" },
                new City { Id = 292, GovernorateId = 18, NameAr = "حى الضواحى", NameEn = "Aldawahi" },
                new City { Id = 293, GovernorateId = 18, NameAr = "حى المناخ", NameEn = "Almanakh" },
                new City { Id = 294, GovernorateId = 18, NameAr = "حى مبارك", NameEn = "Mubarak" },
                new City { Id = 295, GovernorateId = 19, NameAr = "دمياط", NameEn = "Damietta" },
                new City { Id = 296, GovernorateId = 19, NameAr = "دمياط الجديدة", NameEn = "New Damietta" },
                new City { Id = 297, GovernorateId = 19, NameAr = "رأس البر", NameEn = "Ras El Bar" },
                new City { Id = 298, GovernorateId = 19, NameAr = "فارسكور", NameEn = "Faraskour" },
                new City { Id = 299, GovernorateId = 19, NameAr = "الزرقا", NameEn = "Zarqa" },
                new City { Id = 300, GovernorateId = 19, NameAr = "السرو", NameEn = "alsaru" },
                new City { Id = 301, GovernorateId = 19, NameAr = "الروضة", NameEn = "alruwda" },
                new City { Id = 302, GovernorateId = 19, NameAr = "كفر البطيخ", NameEn = "Kafr El-Batikh" },
                new City { Id = 303, GovernorateId = 19, NameAr = "عزبة البرج", NameEn = "Azbet Al Burg" },
                new City { Id = 304, GovernorateId = 19, NameAr = "ميت أبو غالب", NameEn = "Meet Abou Ghalib" },
                new City { Id = 305, GovernorateId = 19, NameAr = "كفر سعد", NameEn = "Kafr Saad" },
                new City { Id = 306, GovernorateId = 20, NameAr = "الزقازيق", NameEn = "Zagazig" },
                new City { Id = 307, GovernorateId = 20, NameAr = "العاشر من رمضان", NameEn = "Al Ashr Men Ramadan" },
                new City { Id = 308, GovernorateId = 20, NameAr = "منيا القمح", NameEn = "Minya Al Qamh" },
                new City { Id = 309, GovernorateId = 20, NameAr = "بلبيس", NameEn = "Belbeis" },
                new City { Id = 310, GovernorateId = 20, NameAr = "مشتول السوق", NameEn = "Mashtoul El Souq" },
                new City { Id = 311, GovernorateId = 20, NameAr = "القنايات", NameEn = "Qenaiat" },
                new City { Id = 312, GovernorateId = 20, NameAr = "أبو حماد", NameEn = "Abu Hammad" },
                new City { Id = 313, GovernorateId = 20, NameAr = "القرين", NameEn = "El Qurain" },
                new City { Id = 314, GovernorateId = 20, NameAr = "ههيا", NameEn = "Hehia" },
                new City { Id = 315, GovernorateId = 20, NameAr = "أبو كبير", NameEn = "Abu Kabir" },
                new City { Id = 316, GovernorateId = 20, NameAr = "فاقوس", NameEn = "Faccus" },
                new City { Id = 317, GovernorateId = 20, NameAr = "الصالحية الجديدة", NameEn = "El Salihia El GedIda" },
                new City { Id = 318, GovernorateId = 20, NameAr = "الإبراهيمية", NameEn = "Al Ibrahimiyah" },
                new City { Id = 319, GovernorateId = 20, NameAr = "ديرب نجم", NameEn = "Deirb Negm" },
                new City { Id = 320, GovernorateId = 20, NameAr = "كفر صقر", NameEn = "Kafr Saqr" },
                new City { Id = 321, GovernorateId = 20, NameAr = "أولاد صقر", NameEn = "Awlad Saqr" },
                new City { Id = 322, GovernorateId = 20, NameAr = "الحسينية", NameEn = "Husseiniya" },
                new City { Id = 323, GovernorateId = 20, NameAr = "صان الحجر القبلية", NameEn = "san alhajar alqablia" },
                new City { Id = 324, GovernorateId = 20, NameAr = "منشأة أبو عمر", NameEn = "Manshayat Abu Omar" },
                new City { Id = 325, GovernorateId = 21, NameAr = "الطور", NameEn = "Al Toor" },
                new City { Id = 326, GovernorateId = 21, NameAr = "شرم الشيخ", NameEn = "Sharm El-Shaikh" },
                new City { Id = 327, GovernorateId = 21, NameAr = "دهب", NameEn = "Dahab" },
                new City { Id = 328, GovernorateId = 21, NameAr = "نويبع", NameEn = "Nuweiba" },
                new City { Id = 329, GovernorateId = 21, NameAr = "طابا", NameEn = "Taba" },
                new City { Id = 330, GovernorateId = 21, NameAr = "سانت كاترين", NameEn = "Saint Catherine" },
                new City { Id = 331, GovernorateId = 21, NameAr = "أبو رديس", NameEn = "Abu Redis" },
                new City { Id = 332, GovernorateId = 21, NameAr = "أبو زنيمة", NameEn = "Abu Zenaima" },
                new City { Id = 333, GovernorateId = 21, NameAr = "رأس سدر", NameEn = "Ras SIdr" },
                new City { Id = 334, GovernorateId = 22, NameAr = "كفر الشيخ", NameEn = "Kafr El Sheikh" },
                new City { Id = 335, GovernorateId = 22, NameAr = "وسط البلد كفر الشيخ", NameEn = "Kafr El Sheikh Downtown" },
                new City { Id = 336, GovernorateId = 22, NameAr = "دسوق", NameEn = "Desouq" },
                new City { Id = 337, GovernorateId = 22, NameAr = "فوه", NameEn = "Fooh" },
                new City { Id = 338, GovernorateId = 22, NameAr = "مطوبس", NameEn = "Metobas" },
                new City { Id = 339, GovernorateId = 22, NameAr = "برج البرلس", NameEn = "Burg Al Burullus" },
                new City { Id = 340, GovernorateId = 22, NameAr = "بلطيم", NameEn = "Baltim" },
                new City { Id = 341, GovernorateId = 22, NameAr = "مصيف بلطيم", NameEn = "Masief Baltim" },
                new City { Id = 342, GovernorateId = 22, NameAr = "الحامول", NameEn = "Hamol" },
                new City { Id = 343, GovernorateId = 22, NameAr = "بيلا", NameEn = "Bella" },
                new City { Id = 344, GovernorateId = 22, NameAr = "الرياض", NameEn = "Riyadh" },
                new City { Id = 345, GovernorateId = 22, NameAr = "سيدي سالم", NameEn = "SIdi Salm" },
                new City { Id = 346, GovernorateId = 22, NameAr = "قلين", NameEn = "Qellen" },
                new City { Id = 347, GovernorateId = 22, NameAr = "سيدي غازي", NameEn = "SIdi Ghazi" },
                new City { Id = 348, GovernorateId = 23, NameAr = "مرسى مطروح", NameEn = "Marsa Matrouh" },
                new City { Id = 349, GovernorateId = 23, NameAr = "الحمام", NameEn = "El Hamam" },
                new City { Id = 350, GovernorateId = 23, NameAr = "العلمين", NameEn = "Alamein" },
                new City { Id = 351, GovernorateId = 23, NameAr = "الضبعة", NameEn = "Dabaa" },
                new City { Id = 352, GovernorateId = 23, NameAr = "النجيلة", NameEn = "Al-Nagila" },
                new City { Id = 353, GovernorateId = 23, NameAr = "سيدي براني", NameEn = "SIdi Brani" },
                new City { Id = 354, GovernorateId = 23, NameAr = "السلوم", NameEn = "Salloum" },
                new City { Id = 355, GovernorateId = 23, NameAr = "سيوة", NameEn = "Siwa" },
                new City { Id = 356, GovernorateId = 23, NameAr = "مارينا", NameEn = "Marina" },
                new City { Id = 357, GovernorateId = 23, NameAr = "الساحل الشمالى", NameEn = "North Coast" },
                new City { Id = 358, GovernorateId = 24, NameAr = "الأقصر", NameEn = "Luxor" },
                new City { Id = 359, GovernorateId = 24, NameAr = "الأقصر الجديدة", NameEn = "New Luxor" },
                new City { Id = 360, GovernorateId = 24, NameAr = "إسنا", NameEn = "Esna" },
                new City { Id = 361, GovernorateId = 24, NameAr = "طيبة الجديدة", NameEn = "New Tiba" },
                new City { Id = 362, GovernorateId = 24, NameAr = "الزينية", NameEn = "Al ziynia" },
                new City { Id = 363, GovernorateId = 24, NameAr = "البياضية", NameEn = "Al Bayadieh" },
                new City { Id = 364, GovernorateId = 24, NameAr = "القرنة", NameEn = "Al Qarna" },
                new City { Id = 365, GovernorateId = 24, NameAr = "أرمنت", NameEn = "Armant" },
                new City { Id = 366, GovernorateId = 24, NameAr = "الطود", NameEn = "Al Tud" },
                new City { Id = 367, GovernorateId = 25, NameAr = "قنا", NameEn = "Qena" },
                new City { Id = 368, GovernorateId = 25, NameAr = "قنا الجديدة", NameEn = "New Qena" },
                new City { Id = 369, GovernorateId = 25, NameAr = "ابو طشت", NameEn = "Abu Tesht" },
                new City { Id = 370, GovernorateId = 25, NameAr = "نجع حمادي", NameEn = "Nag Hammadi" },
                new City { Id = 371, GovernorateId = 25, NameAr = "دشنا", NameEn = "Deshna" },
                new City { Id = 372, GovernorateId = 25, NameAr = "الوقف", NameEn = "Alwaqf" },
                new City { Id = 373, GovernorateId = 25, NameAr = "قفط", NameEn = "Qaft" },
                new City { Id = 374, GovernorateId = 25, NameAr = "نقادة", NameEn = "Naqada" },
                new City { Id = 375, GovernorateId = 25, NameAr = "فرشوط", NameEn = "Farshout" },
                new City { Id = 376, GovernorateId = 25, NameAr = "قوص", NameEn = "Quos" },
                new City { Id = 377, GovernorateId = 26, NameAr = "العريش", NameEn = "Arish" },
                new City { Id = 378, GovernorateId = 26, NameAr = "الشيخ زويد", NameEn = "Sheikh ZowaId" },
                new City { Id = 379, GovernorateId = 26, NameAr = "نخل", NameEn = "Nakhl" },
                new City { Id = 380, GovernorateId = 26, NameAr = "رفح", NameEn = "Rafah" },
                new City { Id = 381, GovernorateId = 26, NameAr = "بئر العبد", NameEn = "Bir al-Abed" },
                new City { Id = 382, GovernorateId = 26, NameAr = "الحسنة", NameEn = "Al Hasana" },
                new City { Id = 383, GovernorateId = 27, NameAr = "سوهاج", NameEn = "Sohag" },
                new City { Id = 384, GovernorateId = 27, NameAr = "سوهاج الجديدة", NameEn = "Sohag El GedIda" },
                new City { Id = 385, GovernorateId = 27, NameAr = "أخميم", NameEn = "Akhmeem" },
                new City { Id = 386, GovernorateId = 27, NameAr = "أخميم الجديدة", NameEn = "Akhmim El GedIda" },
                new City { Id = 387, GovernorateId = 27, NameAr = "البلينا", NameEn = "Albalina" },
                new City { Id = 388, GovernorateId = 27, NameAr = "المراغة", NameEn = "El Maragha" },
                new City { Id = 389, GovernorateId = 27, NameAr = "المنشأة", NameEn = "almunsha'a" },
                new City { Id = 390, GovernorateId = 27, NameAr = "دار السلام", NameEn = "Dar AISalaam" },
                new City { Id = 391, GovernorateId = 27, NameAr = "جرجا", NameEn = "Gerga" },
                new City { Id = 392, GovernorateId = 27, NameAr = "جهينة الغربية", NameEn = "Jahina Al Gharbia" },
                new City { Id = 393, GovernorateId = 27, NameAr = "ساقلته", NameEn = "Saqilatuh" },
                new City { Id = 394, GovernorateId = 27, NameAr = "طما", NameEn = "Tama" },
                new City { Id = 395, GovernorateId = 27, NameAr = "طهطا", NameEn = "Tahta" },
                new City { Id = 396, GovernorateId = 27, NameAr = "الكوثر", NameEn = "Alkawthar" }
                );
            #endregion
            base.OnModelCreating(modelBuilder);
        }
        //protected overrIde voId OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    optionsBuilder
        //        //.UseLazyLoadingProxies()
        //        .UseSqlServer(@"Data Source=.; Initial Catalog=Marasim; 
        //            Integrated Security=True; TrustServerCertificate=True");

        //    //optionsBuilder.UseSqlServer(@"Data Source=localhost; Initial Catalog=Marasim; TrustServerCertificate=True; User Id=SA; Password=$aMer2030");
        //    base.OnConfiguring(optionsBuilder);
        //}

    }
}
